import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SearchBar from "./components/searchbar";
import Navbar from "./components/NavBar";
import Link from "next/link";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <header className="bg-gray-900 flex sm:pt-2 justify-between px-4">
          <Link href="/" className="logo text-white pt-2 pb-3 sm:block hidden">
            Free Videos
          </Link>
          <SearchBar />
        </header>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
